### ISSUE TITLE
Visual Studio Extensibility Checklist

### ISSUE THREAD

**Issue by Peled-Zohar** [Peled-Zohar/AutoEntityGenerator#3]
Follow the [Visual Studio Extensibility Checklist](https://gist.github.com/madskristensen/7310c0d61694e323f4deeb5a70f35fec) to ensure it meets the minimum requirements for a high-quality extension.

* [x] Adhere to threading rules
* [x] Use high-quality icon
* [x] Add descriptive name and description
* [x] Write good Marketplace description
* [x] Add license
* [x] Add privacy notice if applicable
* [x] Use KnownMonikers when possible
* [x] Make it feel native to VS
* [x] Use proper version ranges
